language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - os: linux
      rust: stable
      compiler: gcc
    - os: linux
      rust: beta
      compiler: gcc
    - os: linux
      rust: nightly
      compiler: gcc

    - os: windows
      rust: stable
    - os: windows
      rust: beta
    - os: windows
      rust: nightly

    - os: osx
      rust: stable
    - os: osx
      rust: beta
    - os: osx
      rust: nightly
