language: rust
sudo: false

cache: cargo

matrix:
    fast_finish: true
    include:
      - os: linux
        rust: nightly
        compiler: gcc

      - os: windows
        rust: nightly

      - os: osx
        rust: nightly

script:
  - cargo update
  - cargo test --all --all-features
